name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:22.4
        options: >-
          --health-cmd "clickhouse-client -q 'select 1'" --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 9000:9000

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: make test
        env:
          CH: clickhouse://localhost:9000/default?sslmode=disable
